name: Angular CICD
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:

env:
  AZURE_WEBAPP_NAME: mchipangulardemo
  AZURE_WEBAPP_PACKAGE_PATH: '.'    

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm ci
          npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: "Compilar app"
        run: |
          npm ci
          npm run build
      
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            Dockerfile
            dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      
      - name: "Azure ACR Login"
        uses: azure/docker-login@v1
        with:
          login-server: mchipacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: "Azure Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and push docker image
        run: |
          docker build . -t mchipacr.azurecr.io/angular-hello-word:${{ github.sha }}
          docker push mchipacr.azurecr.io/angular-hello-word:${{ github.sha }} 
      - name: Set Web App ACR authentication
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
                {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "${{ secrets.REGISTRY_PASSWORD }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "mchipacr.azurecr.io",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value": "${{ secrets.REGISTRY_USERNAME  }}",
                    "slotSetting": false
                }
            ]
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: "mchipacr.azurecr.io/angular-hello-word:${{ github.sha }}"
        
