name: Angular CICD
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
        npm ci
        npm test
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: "Ejecutar SCA"
        run: |
          echo "Ejecutando SCA...."
  build:
    runs-on: ubuntu-latest
    needs: [test,sca]
    steps:
      - name: "Compilando codigo"
        run: |
          echo "Compilando...."
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: "Desplegando aplicacion"
        run: |
          echo "Desplegando...."
    
