name: Angular CICD
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:

env:
  AZURE_WEBAPP_NAME: mchipangulardemo
  AZURE_WEBAPP_PACKAGE_PATH: '.'    

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm ci
          npm test

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=miguelch96-github
            -Dsonar.projectKey=angular-hello-world
            -Dsonar.projectVersion=1.0.0
            -Dsonar.sources=./src

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: "Compilar app"
        run: |
          npm ci
          npm run build
      
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            Dockerfile
            dist
  
  publish-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      
      - name: "Azure ACR Login"
        uses: azure/docker-login@v1
        with:
          login-server: mchipacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push docker image
        run: |
          docker build . -t mchipacr.azurecr.io/angular-hello-word:${{ github.sha }}
          docker push mchipacr.azurecr.io/angular-hello-word:${{ github.sha }} 

  deploy:
    uses: ./.github/workflows/deploy-web-apps.yml
    with:
      registry-url: mchipacr.azurecr.io
      image: mchipacr.azurecr.io/angular-hello-word:${{ github.sha }}
      webapp-name: mchipangulardemo
    secrets:
      REGISTRY_USERNAME:  ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD:  ${{ secrets.REGISTRY_PASSWORD }}
      AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
        

          
        
